# Stable rustfmt configuration
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
match_block_trailing_comma = false
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
match_arm_leading_pipes = "Never"
fn_params_layout = "Tall"